// <auto-generated />
using DataProcessingApp.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataProcessingApp.DataAccess.Migrations
{
    [DbContext(typeof(ActuarialDbContext))]
    partial class ActuarialDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataProcessingApp.Core.DataObjects.MortalityTableRow", b =>
                {
                    b.Property<int>("Age")
                        .HasColumnType("int")
                        .HasColumnName("Age");

                    b.Property<double>("Lx")
                        .HasColumnType("float")
                        .HasColumnName("lx");

                    b.Property<int>("Year")
                        .HasColumnType("int")
                        .HasColumnName("Year");

                    b.ToTable("tblMortality", (string)null);
                });

            modelBuilder.Entity("DataProcessingApp.Core.DataObjects.TableBRow", b =>
                {
                    b.Property<double>("PvAnnuity")
                        .HasColumnType("float")
                        .HasColumnName("pvAnnuity");

                    b.Property<double>("PvIncomeInterest")
                        .HasColumnType("float")
                        .HasColumnName("pvIncomeInterest");

                    b.Property<double>("PvRemainderInterest")
                        .HasColumnType("float")
                        .HasColumnName("pvRemainderInterest");

                    b.Property<double>("Rate")
                        .HasColumnType("float")
                        .HasColumnName("Rate");

                    b.Property<double>("Years")
                        .HasColumnType("float")
                        .HasColumnName("Years");

                    b.ToTable("tblB", (string)null);
                });

            modelBuilder.Entity("DataProcessingApp.Core.DataObjects.TableCRow", b =>
                {
                    b.Property<int>("Age")
                        .HasColumnType("int")
                        .HasColumnName("Age");

                    b.Property<double>("DFactor")
                        .HasColumnType("float")
                        .HasColumnName("dFactor");

                    b.Property<int>("MortalityTable")
                        .HasColumnType("int")
                        .HasColumnName("MortalityTable");

                    b.Property<double>("RFactor")
                        .HasColumnType("float")
                        .HasColumnName("rFactor");

                    b.Property<double>("Rate")
                        .HasColumnType("float")
                        .HasColumnName("Rate");

                    b.Property<double>("RemainderFactor")
                        .HasColumnType("float")
                        .HasColumnName("remainderFactor");

                    b.ToTable("tblC", (string)null);
                });

            modelBuilder.Entity("DataProcessingApp.Core.DataObjects.TableDRow", b =>
                {
                    b.Property<double>("PayoutRate")
                        .HasColumnType("float")
                        .HasColumnName("PayoutRate");

                    b.Property<double>("RemainderInterest")
                        .HasColumnType("float")
                        .HasColumnName("remainderInterest");

                    b.Property<int>("Years")
                        .HasColumnType("int")
                        .HasColumnName("Years");

                    b.ToTable("tblD", (string)null);
                });

            modelBuilder.Entity("DataProcessingApp.Core.DataObjects.TableFRow", b =>
                {
                    b.Property<double>("AdjustmentFactor")
                        .HasColumnType("float")
                        .HasColumnName("adjustmentFactor");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Frequency");

                    b.Property<double>("InterestRate")
                        .HasColumnType("float")
                        .HasColumnName("InterestRate");

                    b.Property<int>("Months")
                        .HasColumnType("int")
                        .HasColumnName("Months");

                    b.ToTable("tblF", (string)null);
                });

            modelBuilder.Entity("DataProcessingApp.Core.DataObjects.TableHRow", b =>
                {
                    b.Property<int>("Age")
                        .HasColumnType("int")
                        .HasColumnName("Age");

                    b.Property<double>("DFactor")
                        .HasColumnType("float")
                        .HasColumnName("dFactor");

                    b.Property<double>("InterestRate")
                        .HasColumnType("float")
                        .HasColumnName("InterestRate");

                    b.Property<double>("MFactor")
                        .HasColumnType("float")
                        .HasColumnName("mFactor");

                    b.Property<int>("MortalityTable")
                        .HasColumnType("int")
                        .HasColumnName("MortalityTable");

                    b.Property<double>("NFactor")
                        .HasColumnType("float")
                        .HasColumnName("nFactor");

                    b.ToTable("tblH", (string)null);
                });

            modelBuilder.Entity("DataProcessingApp.Core.DataObjects.TableJRow", b =>
                {
                    b.Property<double>("AdjustmentFactor")
                        .HasColumnType("float")
                        .HasColumnName("adjustmentFactor");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Frequency");

                    b.Property<double>("InterestRate")
                        .HasColumnType("float")
                        .HasColumnName("InterestRate");

                    b.ToTable("tblJ", (string)null);
                });

            modelBuilder.Entity("DataProcessingApp.Core.DataObjects.TableKRow", b =>
                {
                    b.Property<double>("AdjustmentFactor")
                        .HasColumnType("float")
                        .HasColumnName("adjustmentFactor");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Frequency");

                    b.Property<double>("InterestRate")
                        .HasColumnType("float")
                        .HasColumnName("InterestRate");

                    b.ToTable("tblK", (string)null);
                });

            modelBuilder.Entity("DataProcessingApp.Core.DataObjects.TableR2Row", b =>
                {
                    b.Property<double>("AdjustedPayoutRate")
                        .HasColumnType("float")
                        .HasColumnName("AdjustedPayoutRate");

                    b.Property<int>("Age1")
                        .HasColumnType("int")
                        .HasColumnName("Age1");

                    b.Property<int>("Age2")
                        .HasColumnType("int")
                        .HasColumnName("Age2");

                    b.Property<int>("MortalityTable")
                        .HasColumnType("int")
                        .HasColumnName("MortalityTable");

                    b.Property<double>("RemainderFactor")
                        .HasColumnType("float")
                        .HasColumnName("remainderFactor");

                    b.ToTable("tblR2", (string)null);
                });

            modelBuilder.Entity("DataProcessingApp.Core.DataObjects.TableSRow", b =>
                {
                    b.Property<int>("Age")
                        .HasColumnType("int")
                        .HasColumnName("Age");

                    b.Property<double>("InterestRate")
                        .HasColumnType("float")
                        .HasColumnName("InterestRate");

                    b.Property<int>("MortalityTable")
                        .HasColumnType("int")
                        .HasColumnName("MortalityTable");

                    b.Property<double>("PvAnnuity")
                        .HasColumnType("float")
                        .HasColumnName("pvAnnuity");

                    b.Property<double>("PvLifeEstate")
                        .HasColumnType("float")
                        .HasColumnName("pvLifeEstate");

                    b.Property<double>("PvReminderInterest")
                        .HasColumnType("float")
                        .HasColumnName("pvRemainderInterest");

                    b.ToTable("tblS", (string)null);
                });

            modelBuilder.Entity("DataProcessingApp.Core.DataObjects.TableU1Row", b =>
                {
                    b.Property<double>("AdjustedPayoutRate")
                        .HasColumnType("float")
                        .HasColumnName("AdjustedPayoutRate");

                    b.Property<int>("Age")
                        .HasColumnType("int")
                        .HasColumnName("Age");

                    b.Property<int>("MortalityTable")
                        .HasColumnType("int")
                        .HasColumnName("MortalityTable");

                    b.Property<double>("RemainderFactor")
                        .HasColumnType("float")
                        .HasColumnName("remainderFactor");

                    b.ToTable("tblU1", (string)null);
                });

            modelBuilder.Entity("DataProcessingApp.Core.DataObjects.TableU2Row", b =>
                {
                    b.Property<double>("AdjustedPayoutRate")
                        .HasColumnType("float")
                        .HasColumnName("AdjustedPayoutRate");

                    b.Property<int>("Age1")
                        .HasColumnType("int")
                        .HasColumnName("Age1");

                    b.Property<int>("Age2")
                        .HasColumnType("int")
                        .HasColumnName("Age2");

                    b.Property<int>("MortalityTable")
                        .HasColumnType("int")
                        .HasColumnName("MortalityTable");

                    b.Property<double>("RemainderFactor")
                        .HasColumnType("float")
                        .HasColumnName("remainderFactor");

                    b.ToTable("tblU2", (string)null);
                });

            modelBuilder.Entity("DataProcessingApp.Core.DataObjects.TableZRow", b =>
                {
                    b.Property<int>("Age")
                        .HasColumnType("int")
                        .HasColumnName("Age");

                    b.Property<double>("DFactor")
                        .HasColumnType("float")
                        .HasColumnName("dFactor");

                    b.Property<double>("InterestRate")
                        .HasColumnType("float")
                        .HasColumnName("InterestRate");

                    b.Property<double>("MFactor")
                        .HasColumnType("float")
                        .HasColumnName("mFactor");

                    b.Property<int>("MortalityTable")
                        .HasColumnType("int")
                        .HasColumnName("MortalityTable");

                    b.Property<double>("NFactor")
                        .HasColumnType("float")
                        .HasColumnName("nFactor");

                    b.ToTable("tblZ", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
